In [4]:
import pandas as pd
print(pd.__version__)

3.0.6

In [3]:
from pathlib import Path
Path.cwd()

WindowsPath('c:/Users/belov/Desktop/womens-health-screening/notebooks')

In [5]:
file_path = Path("../data/raw/hlth_ehis_pa7e__custom_22838814_linear_2_0.csv.gz")
df = pd.read_csv(file_path)
df.shape

(9996, 23)

In [6]:
df.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency',
       'unit', 'Unit of measure', 'duration', 'Duration', 'isced11',
       'International Standard Classification of Education (ISCED 2011)',
       'age', 'Age class', 'geo', 'Geopolitical entity (reporting)',
       'TIME_PERIOD', 'Time', 'OBS_VALUE', 'Observation value', 'OBS_FLAG',
       'Observation status (Flag) V2 structure', 'CONF_STATUS',
       'Confidentiality status (flag)'],
      dtype='str')

In [7]:
df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,duration,Duration,isced11,...,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:HLTH_EHIS_PA7E(1.0),Self-reported last breast examination by X-ray...,A,Annual,PC,Percentage,NEV,Never,ED0-2,...,AT,Austria,2014,NaN,27.6,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:HLTH_EHIS_PA7E(1.0),Self-reported last breast examination by X-ray...,A,Annual,PC,Percentage,NEV,Never,ED0-2,...,AT,Austria,2019,NaN,28.0,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:HLTH_EHIS_PA7E(1.0),Self-reported last breast examination by X-ray...,A,Annual,PC,Percentage,NEV,Never,ED0-2,...,BE,Belgium,2014,NaN,35.1,NaN,u,low reliability,NaN,NaN
3,dataflow,ESTAT:HLTH_EHIS_PA7E(1.0),Self-reported last breast examination by X-ray...,A,Annual,PC,Percentage,NEV,Never,ED0-2,...,BE,Belgium,2019,NaN,43.2,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:HLTH_EHIS_PA7E(1.0),Self-reported last breast examination by X-ray...,A,Annual,PC,Percentage,NEV,Never,ED0-2,...,BG,Bulgaria,2014,NaN,73.4,NaN,NaN,NaN,NaN,NaN

In [9]:
df["duration"].value_counts()

duration
NEV      1820
Y1-2     1820
Y2-3     1820
Y_GE3    1820
Y_LT1    1820
Y_LT2     896
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9996 entries, 0 to 9995
Data columns (total 23 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   STRUCTURE                                                        9996 non-null   str
 1   STRUCTURE_ID                                                     9996 non-null   str
 2   STRUCTURE_NAME                                                   9996 non-null   str
 3   freq                                                             9996 non-null   str
 4   Time frequency                                                   9996 non-null   str
 5   unit                                                             9996 non-null   str
 6   Unit of measure                                                  9996 non-null   str
 7   duration                                                         9996 non-null   str
 8   Duration                                                         9996 non-null   str
 9   isced11                                                          9996 non-null   str
 10  International Standard Classification of Education (ISCED 2011)  9996 non-null   str
 11  age                                                              9996 non-null   str
 12  Age class                                                        9996 non-null   str
 13  geo                                                              9996 non-null   str
 14  Geopolitical entity (reporting)                                  9996 non-null   str
 15  TIME_PERIOD                                                      9996 non-null   int64
 16  Time                                                             0 non-null      float64
 17  OBS_VALUE                                                        9851 non-null   float64
 18  Observation value                                                0 non-null      float64
 19  OBS_FLAG                                                         745 non-null    str
 20  Observation status (Flag) V2 structure                           745 non-null    str
 21  CONF_STATUS                                                      0 non-null      float64
 22  Confidentiality status (flag)                                    0 non-null      float64
dtypes: float64(5), int64(1), str(17)
memory usage: 1.8 MB

In [10]:
pd.crosstab(df["duration"], df["TIME_PERIOD"])

TIME_PERIOD  2014  2019
duration
NEV           924   896
Y1-2          924   896
Y2-3          924   896
Y_GE3         924   896
Y_LT1         924   896
Y_LT2           0   896

In [11]:
df["OBS_FLAG"].value_counts(dropna=False)

OBS_FLAG
NaN    9251
u       689
d        50
du        6
Name: count, dtype: int64

In [12]:
df[df["OBS_VALUE"].isna()].head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,duration,Duration,isced11,...,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
98,dataflow,ESTAT:HLTH_EHIS_PA7E(1.0),Self-reported last breast examination by X-ray...,A,Annual,PC,Percentage,NEV,Never,ED0-2,...,IS,Iceland,2014,NaN,NaN,NaN,u,low reliability,NaN,NaN
99,dataflow,ESTAT:HLTH_EHIS_PA7E(1.0),Self-reported last breast examination by X-ray...,A,Annual,PC,Percentage,NEV,Never,ED0-2,...,IS,Iceland,2019,NaN,NaN,NaN,u,low reliability,NaN,NaN
138,dataflow,ESTAT:HLTH_EHIS_PA7E(1.0),Self-reported last breast examination by X-ray...,A,Annual,PC,Percentage,NEV,Never,ED0-2,...,CZ,Czechia,2014,NaN,NaN,NaN,u,low reliability,NaN,NaN
142,dataflow,ESTAT:HLTH_EHIS_PA7E(1.0),Self-reported last breast examination by X-ray...,A,Annual,PC,Percentage,NEV,Never,ED0-2,...,DK,Denmark,2014,NaN,NaN,NaN,u,low reliability,NaN,NaN
143,dataflow,ESTAT:HLTH_EHIS_PA7E(1.0),Self-reported last breast examination by X-ray...,A,Annual,PC,Percentage,NEV,Never,ED0-2,...,DK,Denmark,2019,NaN,NaN,NaN,u,low reliability,NaN,NaN

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.duplicated(
    subset=["geo", "TIME_PERIOD", "age", "isced11", "duration"]
).sum()

np.int64(0)

In [15]:
df["OBS_VALUE"].describe()

count    9851.000000
mean       21.137255
std        23.266143
min         0.000000
25%         5.200000
50%        12.200000
75%        28.900000
max       100.000000
Name: OBS_VALUE, dtype: float64

размеры таблицы (9996, 23);
незаполненных строк в столбце OBS_VALUE 145, т.е. для 145 наблюдений значение не заполнено;
абсолютно идентичных строк нет;
дубликатов в связке "geo", "TIME_PERIOD", "age", "isced11", "duration" нет;
Y_LT2(последнее обследование груди было менее двух лет назад) есть только за 2019 год;
Важная точность для проекта: это данные самоотчёта о последнем обследовании, а не подтверждённое число участниц организованной программы скрининга.

In [16]:
df["OBS_VALUE"].isna().sum()

np.int64(145)